name: Release-Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version_number: ${{ steps.version_number.outputs.version_number }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go 1.26
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"
        id: go

      - name: Version Number
        id: version_number
        run: echo "version_number=$(make version_number)" >> $GITHUB_OUTPUT

      - name: Show Version
        run: echo "Version ${{ steps.version_number.outputs.version_number }}"

      - name: Build
        run: make prepare build archive

      - name: "Upload binary archive"
        uses: actions/upload-artifact@v7
        with:
          name: hcplugin-archive
          path: ./com.thecodingflow.hcplugin.zip

      - name: Upload package to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./com.thecodingflow.hcplugin.zip
          asset_name: com.thecodingflow.hcplugin.zip
          overwrite: true
